FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Devices

Devices is a list of devices

## Questions Devices [/devices]

### List All Devices [GET]

+ Response 200 (application/json)

        [
            {
                "devices": "All your Devices?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "01",
                        "votes": 2048
                    }, {
                        "choice": "02",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "xxx",
                "yyy",
                "ccc",
                "dddd"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "xxx",
                        "votes": 0
                    }, {
                        "choice": "yyy",
                        "votes": 0
                    }, {
                        "choice": "dddd",
                        "votes": 0
                    }, {
                        "choice": "ccc",
                        "votes": 0
                    }
                ]
            }